# Generated by Django 5.1.1 on 2025-03-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('scheme', models.CharField(max_length=255)),
                ('income', models.PositiveIntegerField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
