# Generated by Django 5.1.1 on 2025-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schemeapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
