# Generated by Django 5.1.1 on 2025-04-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_complaint_is_approved_schemeapplication_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeapplication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
