# Generated by Django 5.1.1 on 2025-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_schemeapplication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeapplication',
            name='aadhaar',
            field=models.CharField(max_length=12),
        ),
    ]
